Added info button
OctoPi-Team/OctoPi pull request #117
Opened 2023-06-14 12:43 UTC by timowenz

2023-06-14 13:38 UTC, pIlIp-d requested changes
On high resolution screen the box height is smaller than the text height.
please make height scale with text height.

2023-06-14 19:12 UTC, timowenz commented
Kannst du ein Bild machen? Weiß nicht ganz genau was du meinst. Habs responsive ausprobiert.

2023-06-15 08:13 UTC, pIlIp-d commented
![image](https://github.com/OctoPi-Team/OctoPi/assets/62812264/14db54ce-348c-4c41-8212-95816206222d)

2023-06-16 11:29 UTC, pIlIp-d approved these changes

2023-06-16 11:29 UTC, merged